"""Add roles

Revision ID: 4a8bd88c96f1
Revises: a5455d52f524
Create Date: 2025-06-17 04:45:17.366013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "4a8bd88c96f1"
down_revision: Union[str, None] = "a5455d52f524"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

userrole = postgresql.ENUM("USER", "ADMIN", name="userrole")


def upgrade() -> None:
    """Upgrade schema."""
    userrole.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Додаємо колонку, але nullable=True (дозволяємо null)
    op.add_column("users", sa.Column("role", userrole, nullable=True))

    # 2. Оновлюємо всі існуючі записи, ставлячи роль 'USER' за замовчуванням
    op.execute("UPDATE users SET role = 'USER' WHERE role IS NULL")

    # 3. Змінюємо колонку на nullable=False (NOT NULL)
    op.alter_column("users", "role", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
